---
- name: Configure Apache in webservers
  hosts: webservers
  become: yes
  tasks:
   - name: Include vars from dummy_vars.yml
     include_vars: dummy_vars.yml

   - name: Override index_file 
     set_fact: 
       index_file: demo2.html
       test_file: "{{ ansible_distribution }}.txt"

   - name: Install Apache
     package:
       name: "{{ web_package }}"
       state: latest

   - name: "Copy {{ index_file }} under {{ webserver_root_path }}"
     copy: 
       src: "{{ index_file }}"
       dest: "{{ webserver_root_path }}/{{index_file }}"
       owner: "{{ web_user }}"
       group: "{{ web_user }}"
       mode: 0777

   - name: Start and Enable Apache
     service: 
       name:  "{{ web_service }}"
       state: started
       enabled: yes

   - name: Check if apache is running
     wait_for:
       port: 80
       state: started

   - name: Get content from apache webserver
     uri:
       url: "http://{{ ansible_hostname }}/{{ index_file }}"
       method: GET
       return_content: yes
     register: web_output     

   - name: Display web page output
     debug:
       msg: 
         - "Web Content is {{ web_output.content | trim }}"
         - "test_file name is {{ test_file }}"

