---
- hosts: all
  gather_facts: false
  become: yes
  tasks: 
    - name: "Get the list of files from /"
      shell:
        "ls"
      args:
        chdir: "/"
      register: root_files_op


    - name: get metadata for filesystem
      stat: 
        path: "/{{ item }}"
      register: filesys_meta
      loop: "{{ root_files_op.stdout_lines }}"

    - debug: 
        msg: 
         - "Filesystem: {{ item.item }}"
         - "Size:       {{ item.stat.size }}"
      when: (item.stat.size | int) > 500
      loop: "{{ filesys_meta.results }}"
