---
- hosts: all
  gather_facts: false
  become: yes
  tasks: 
    - name: "Get the list of files from /"
      shell:
        "ls"
      args:
        chdir: "/"
      register: root_files_op

    - debug: 
        msg: "{{ item }}"
      loop: root_files_op.stdout_lines
